### ISSUE TITLE
Cannot use the same key at the same time

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#11]
Getting this error:
Mirie Mahpour@LAPTOP-SB1C5E50 MINGW64 ~/dinar-trader (master)

> $ python exchange_query.py
> Kraken session configured.
> Gemini session configured.
> Fetching exchange data...
> Traceback (most recent call last):
>   File "exchange_query.py", line 16, in <module>
>     kbalances = kraken.get_balances()
>   File "C:\Users\Mirie Mahpour\dinar-trader\exchange_session.py", line 34, in get_balances
>     balance = self.session.query_private('Balance')['result']
> KeyError: 'result'

Did Kraken change their API?

**Comment by bustoutfunk** [comment]
@adamhyman I found out the issue. There is a problem with sharing the API key for some reason. Apparently the bug was filed [here](https://github.com/timmolter/XChange/issues/624). Have you run into this issue at all? I don't really understand what it means.

**Comment by bustoutfunk** [comment]
It looks like we need to have unique API keys per machine. According to [this](https://github.com/timmolter/XChange/issues/624) issue it's recommended that every thread has it's own API key.

@adamhyman, can you generate additional API keys for me?

**Comment by adamhyman** [comment]
@bustoutfunk, I just emailed you your keys.



 - Adam Hyman

**Comment by adamhyman** [comment]
If they work, please close the issue.

**Comment by bustoutfunk** [comment]
Tested out new API keys and they work.
