### ISSUE TITLE
Generate sample GDAX code

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#13]
Write a simple script that demonstrates the following using the GDAX API:

1. Checking balances
1. Get bid/ask price of ETH to USD
1. Buying shares
1. Selling share

...just like what had been done with the original code. This will help me fold in the GDAX API into exchange_session.py.

**Comment by adamhyman** [comment]
Done!

The only issue is that it currently only works when the code is run from the gdax-python folder.

The lines which trade are commented out.  So just uncomment them to make the trade.

**Comment by bustoutfunk** [comment]
@adamhyman, I spent quite a bit of time trying to find a way to run the code outside of the gdax folder. Unfortunately, the way the code was written does not easily lend itself towards that. I think the best way to resolve this is to just install the library using pip:
`pip install gdax`

I will add this to the README as a prerequisite.

**Comment by bustoutfunk** [comment]
Got an error when trying to run:
```
$ python Sample\ GDAX\ Code.py
Ticker:  {'trade_id': 7323349, 'price': '215.40000000', 'size': '2.08001518', 'bid': '215.42', 'ask': '215.49', 'volume': '224377.12764187', 'time': '2017-07-10T18:57:23.592000Z'}

ETH Ask is 215.49 and ETH Bid is 215.42
BTC Ask is 2399.41 and BTC Bid is 2399.4
auth_client.get_accounts() looks like this:
{'message': 'CB-ACCESS-PASSPHRASE header is required'}
I want to make sure they don't change the order of the currencies.
Traceback (most recent call last):
  File "Sample GDAX Code.py", line 75, in <module>
    update_account_balances ()
  File "Sample GDAX Code.py", line 58, in update_account_balances
    if gdax_accounts[0]['currency'] == 'USD':
KeyError: 0
```
What is the _CB-ACCESS-PASSPHRASE_ header?

**Comment by adamhyman** [comment]
Can you try with the GDAX key I sent you yesterday?

You haven't made any transactions.

**Comment by bustoutfunk** [comment]
Works. Thanks.
