### ISSUE TITLE
Add Submodule for GDAX

### ISSUE THREAD

**Issue by adamhyman** [adamhyman/dinar-trader#5]
Can you add [this submodule](https://github.com/danpaquin/GDAX-Python) for GDAX?

Can you just name it GDAX, instead of GDAX-Python which contains a dash?

**Comment by bustoutfunk** [comment]
@adamhyman, names should be kept exactly how they come from the repo if possible. What is the issue with the dash?

**Comment by adamhyman** [comment]
Python doesn't seem to do well with a dash in a folder name.  It's okay.  I used the import module approach from [here](https://stackoverflow.com/questions/7583652/python-module-with-a-dash-or-hyphen-in-its-name), and it worked.

**Comment by bustoutfunk** [comment]
Too late. I already pushed 😄

**Comment by bustoutfunk** [comment]
Closing the issue per the [60c22e8](https://github.com/adamhyman/dinar-trader/commit/60c22e80e200f62246afd204c48beab3425ccc00) commit.
