### ISSUE TITLE
Create "get_stats" method

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#6]
Commit [6bb039e](https://github.com/adamhyman/dinar-trader/commit/6bb039ecbe11fb17d9e5451377361516916312ea) modularizes the function calls to the exchange servers but is inefficient (as the get balance can be bundles into a single command versus one for each currency). For actual trading operations need to create a method that just returns a dictionary of all the balances.

**Comment by adamhyman** [comment]
You are awesome.

**Comment by bustoutfunk** [comment]
Done per commit (b93a857)[https://github.com/adamhyman/dinar-trader/commit/b93a8571e07b5b37e367ee227f76a76603f648e7].
