### ISSUE TITLE
Bitcoin symbol in Kraken

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#7]
Not sure what symbol to use for Bitcoin in Kraken exchange. Should we be using XBT?

**Comment by adamhyman** [comment]
It is XBT.  It's causing an error because I currently have no Bitcoin in Kraken, so they don't include it at all in the query results.

I just transferred in some bitcoin, so that it will show up in the query results.

It will take a little bit of time for it to show up.

**Comment by bustoutfunk** [comment]
Ok, I will update the code accordingly.

________________________________

**Comment by adamhyman** [comment]
XBT is now in Kraken.

**Comment by bustoutfunk** [comment]
Seems to be working. Closing issue.
