### ISSUE TITLE
GDAX Folder on PC is empty

### ISSUE THREAD

**Issue by adamhyman** [adamhyman/dinar-trader#9]
Do you have any idea why my GDAX folder on my PC is empty?

I think I pulled everything from Github to my PC.

![image](https://user-images.githubusercontent.com/1277113/27719281-23fee092-5d06-11e7-944b-61bdbb47ff2e.png)

**Comment by bustoutfunk** [comment]
Try "git submodule update --init --recursive" and see if it populates.

________________________________

**Comment by bustoutfunk** [comment]
@adamhyman did you get this to work? If so then please close the issue.

**Comment by adamhyman** [comment]
It worked!
